Повторный deploy node, мелкие баги терминала
Automiq/alpha.protort pull request #116
Opened 2016-12-03 12:54 UTC by kimolegan

2016-12-03 15:57 UTC, dstftw requested changes

2016-12-03 15:57 UTC, dstftw commented on components/src/calc.h
> +    calc(boost::shared_ptr<node::router<node::node>> router): component(router)
И для кого интересно алиасы придумали?

2016-12-03 15:57 UTC, dstftw commented
Зачем все свалено в кучу?
Зачем сейчас переход на shared роутер?

2016-12-05 08:28 UTC, dstftw commented
>Зачем все свалено в кучу?
Зачем сейчас переход на shared роутер?

2016-12-05 08:30 UTC, dstftw requested changes

2016-12-05 08:30 UTC, dstftw commented on node/src/node.h
> +            router_->clear();
С чего вдруг здесь делается `clear`?

2016-12-05 21:36 UTC, dstftw requested changes

2016-12-05 21:36 UTC, dstftw commented on node/src/router.h
> +class router : public std::enable_shared_from_this<router<app>>
Ну что, опять по-новой на те же грабли?

2016-12-06 05:13 UTC, kimolegan commented on node/src/router.h
> +class router : public std::enable_shared_from_this<router<app>>
это старый код, еще до исправлений был, те же грабли, но не по-новой

2016-12-06 09:13 UTC, merged