Parser
Automiq/alpha.protort pull request #145
Opened 2017-10-27 07:26 UTC by AlexMonster15

Реализована обработка резервного узла.

2017-10-27 08:53 UTC, Zubatov95 commented on parser/src/parser.h
> +                     auto col_child = v.second.size();// Количество детей у поддерева node.
мб назвать переменную quantity_child. узнать какой тип данных возвращает size буста.

2017-10-27 09:13 UTC, Zubatov95 approved these changes
код логичный, рабочий.
в файле parser.h, предлагаю col_child на quantity_child.

2017-10-27 09:45 UTC, CodingFeles requested changes
Претензии:
* Много бесполезных комментариев: код говорит в этих случаях лучше.
* Замечания по оформлению, но часть замечаний к стилю, который был здесь с самого начала.
* Замечания к именованию.
* Замечание к проверке количества детей.
* Код проверки количества детей убежал из метода parse_node где он должен был быть.
Плюсы: 
* Поддержаны изменения в остальных частях кода.
* Грамотная реструктуризация парсера: добавлены методы парсинга конкретных элементов - это очень хорошо, они там напрашивались.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +* получает и хрании информацию путем парсинга xml файлов схемы приложения
Опечатка: хранит.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    std::string name;// Имя компонента
Такого рода комментарии лучше делать над полем.
И даже лучше делать brief аналогично как в комментарии к структуре.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    std::string kind;// Тип компонента
Стоит разделять члены классов пустыми строками: читать легче.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    port_id dest_in;// Идентификатор входа у получающего компонента
Аналогичные замечания как и выше.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
>   * \brief Класс сетевого узла
Это комментарий к node, а не к Address.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> + * Класс хранит имя, адрес, порт узла и конфигурационный порт узла
Актуализировать комментарий конкретно для структуры адреса.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +struct Address
Стоит следовать принятому именованию: типы здесь именуются с маленькой буквы.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    std::string address;// IP-адрес или hostname узла
Поле address в структуре Address ??? Комментарий - это хорошо, но надо именовать так, чтобы не оставалось сомнений. Предлагаю: ip или ip_address.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    port_id config_port;// Порт сервера конфигурации (по умолчанию =100)
Замечания по комментариям и разделению пустыми строками аналогично тем, что выше.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    boost::optional<Address> pairnode;// Адрес резервной ноды
Замечания по комментариям и разделению пустыми строками аналогично тем, что выше.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
>  struct node
Дописать утерянную аннотацию к структуре.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +    std::string node_name;// Имя узла
Замечания по комментариям и разделению пустыми строками аналогично тем, что выше.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> -            using boost::property_tree::ptree;
Почему этот using был удалён?

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +                     auto col_child = v.second.size();// Количество детей у поддерева node.
Я думаю, что эти проверки должны быть в методе parse_node.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> -            using boost::property_tree::ptree;
Аналогичное исчезновение юзинга. Почему?

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +                                                     + v.second.get<std::string>("<xmlattr>.name")
Лучше использовать форматные строки, а не конкатенацию.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +                     auto col_child = v.second.size();// Количество детей у поддерева node.
col_child лучше переименовать, например, в child_size или child_quantity или child_num.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +                             node noda;
noda - плохое название. current_node можно использовать.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +                     if(col_child > 2)
Так, а почему мы проверяем вокруг 2? Детей у поддерева node должно быть 1. И проверять надо это. Как я понимаю, то тут мы проверяем подветвь, включающую в себя саму node. Надо сделать так: берём узел node, смотрим, что у этого узла уже только один единственный ребёнок.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         noda.name = v.second.get<std::string>("<xmlattr>.name");// Устанавливаем  имя узла, соответстующий иадресу из xml кода
Строчки с комментариями получаются очень длинными. Думаю будет легче читать, если комментарии разместить выше.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         noda.address.config_port = v.second.get<port_id>("<xmlattr>.config_port", 100);// Устанавливаем  конфигурационному порту резервного узла, соответстующий конфигурационный порт из xml кода
Я думаю, что не нужны все эти комментарии. В целом ясно, что происходит. Можно обобщить: "Инициализируем поля узла, исходя из описания в xml."

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +     void parse_node(boost::property_tree::ptree::value_type const &v, node &noda, bool flag = false)
Что такое flag? Плохое имя из которого ничего не понятно. Булевские входные атрибуты, которые разделяют работу метода так или иначе - тоже плохая практика. Обычно, это должно превратиться в два разных метода. Тут я думаю этот флаг уйдёт, если занести проверки на количество детей внутрь в метод, где они и должны быть.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +             Address tmp;
Я думаю, что лучше не tmp, а pair_address.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +             tmp.config_port = v.second.get<port_id>("pairnode.<xmlattr>.config_port", 100);// Устанавливаем  конфигурационному порту резервного узла, соответстующий конфигурационный порт из xml кода
Опять вагончик ненужных комментариев.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         nodes.push_back(noda);// Пушим узел в вектор узлов
Комментарий не нужен.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +     * Метод парсит connection и сохраняет полученную информацию внутри класса в соответствующих атрибутах
Так компонент или коннекшен парсит метод?

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         components.push_back(comp);// Пушим компонент в вектор компонентов
Эти комментарии особо пользы не несут.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         connections.push_back(conn);// Пушим связь в вектор связей
Аналогичная претензия к комментариям: пользы мало.

2017-10-27 09:45 UTC, CodingFeles commented on parser/src/parser.h
> +         mappings.push_back(mapp);// Пушим отображение компонента на сетевой узел в соответствующий вектор
Аналогичная претензия к комментариям: пользы мало.

2017-11-20 04:51 UTC, CodingFeles requested changes
Основные замечания исправлены. Осталось пара серьёзных и некоторые мелочи.

2017-11-20 04:51 UTC, CodingFeles commented on parser/src/parser.h
> +    address address_;
Нижнее подчёркивание - часть имени приватной переменной. Это не тот случай.

2017-11-20 04:51 UTC, CodingFeles commented on parser/src/parser.h
>                  parse_component(v);
Я считаю, что экономить на скобках {} не стоит: меньше ошибок будет.

2017-11-20 04:51 UTC, CodingFeles commented on parser/src/parser.h
> +             throw std::invalid_argument((boost::format("In the node name (%1%): Expected no more than one child node: 'pairnode'")
Я считаю, что экономить на скобках {} не стоит: меньше ошибок будет.

2017-11-20 04:51 UTC, CodingFeles commented on parser/src/parser.h
> +         auto child_size = v.second.size();
Мы здесь детей должны смотреть, а смотрим поддерево, включая узел node. Делаем исходя из этого странные для детей проверки: должен быть только 1 ребёнок, а не 2 и детей вполне может и не быть. Непонятно и нелогично - надо исправить.

2017-11-20 04:51 UTC, CodingFeles commented on parser/src/parser.h
> +             current_node.address_.ip_address = v.second.get<std::string>("<xmlattr>.address");
Нельзя ли код разбора адреса обобщить?

2017-11-21 04:24 UTC, CodingFeles requested changes
Мелочи поправлены. Один серьёзный момент остался проблемный. По второму есть подвижки, но пока неудовлетворительные.

2017-11-21 04:24 UTC, CodingFeles commented on parser/src/parser.h
> +         if(stroka.empty()){
Зачем транслит?

2017-11-21 04:24 UTC, CodingFeles commented on parser/src/parser.h
> +     void init_address(node &current_node, address & host, const ptree::value_type &v, const std::string &stroka = "")
stroka выглядит плохо. Да и она не нужна здесь. Подумай как сделать без неё.

2017-11-21 04:24 UTC, CodingFeles commented on parser/src/parser.h
> +     void init_address(node &current_node, address & host, const ptree::value_type &v, const std::string &stroka = "")
Почему бы результат не возвращать?

2017-11-21 04:24 UTC, CodingFeles commented on parser/src/parser.h
> +         if(stroka.empty()){
Мне кажется, что это плохое условие для проверки того, кому это будем задавать.

2017-11-21 04:24 UTC, CodingFeles commented on parser/src/parser.h
> +             current_node.pairnode = host;
И вообще, стоит ли задавать это здесь?

2017-11-22 09:47 UTC, CodingFeles approved these changes

2017-11-22 09:48 UTC, merged