Uidoc
Automiq/alpha.protort pull request #80
Opened 2016-11-11 07:33 UTC by YaroslavShmakov

Реализован class Documen
Настроено окно конфигураций, добавлен прототип вывода в лог развёртывания информации о ходе развёртывания.
(closes #52) (closes #71 )

2016-11-11 08:11 UTC, dstftw requested changes

2016-11-11 08:11 UTC, dstftw commented on terminal/src/configdialog.cpp
> +void ConfigDialog::loadApp(QList<QString> c_app)
Ненужное копирование списка.

2016-11-11 08:11 UTC, dstftw commented on terminal/src/configdialog.cpp
> +void ConfigDialog::loadDeploy(QList<QString> c_deploy)
Ненужное копирование списка.

2016-11-11 08:11 UTC, dstftw commented on terminal/src/document.cpp
> +        return Kind::Deploy;
В случае `xml.name()` не равного ни `app`, ни `deploy` ничего не вернется.

2016-11-11 08:11 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +        if(tmp == 2)
Зачем тут магические числа вместо енумераторов?

2016-11-11 08:11 UTC, dstftw commented on terminal/src/mainwindow.h
> +    QList <Document> openDeploy;
Зачем эти списки?

2016-11-11 08:11 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +        dlg.loadDeploy(confDeploy);
Форматирование поплыло.

2016-11-11 08:11 UTC, dstftw commented on terminal/src/configdialog.cpp
> +    this->hide();
Это зачем?

2016-11-11 08:11 UTC, dstftw commented on terminal/src/document.cpp
> +//QByteArray Document::txt(){return text;}
Почистить мусор.

2016-11-11 08:11 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +    QString fileName = QFileDialog::getOpenFileName(this, QString ("Открыть файл"), QString(), QString("xml (*.xml);; all (*)"));
Задать внятные имена для фильтра. Все локализуемые строки обернуть в `tr`.

2016-11-14 11:25 UTC, dstftw requested changes

2016-11-14 11:25 UTC, dstftw commented on terminal/src/document.h
> +    QString name;
Мемберы в Qt принято обозначать с преффиксом `m_`.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/configdialog.cpp
> +void ConfigDialog::loadApp(QString &c_app)
Тут нужна константная ссылка - значение `c_app` не меняется.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/document.cpp
> +    name = "";
Оно и так по умолчанию пусто.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/document.cpp
> +    if(name == "")
`name.isEmpty()`.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/document.h
> +    QString getFileNameOFD();
Зачем это в public секции?

2016-11-14 11:25 UTC, dstftw commented on terminal/src/mainwindow.h
> +    QList <Document> openDeploy;
Не исправлено.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +        title = tr("Unnamed");
Не локализовано.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/mainwindow.cpp
>      for (int i = ui->tabWidget->count(); i >= 0; --i)
Валидные индексы лежат в диапазоне `[0; ui->tabWidget->count() - 1]`. `ui->tabWidget->count()` априори невалидный индекс.
Также, не ясно, какой смысл обходить табы задом наперед.

2016-11-14 11:25 UTC, dstftw commented on terminal/src/mainwindow.ui
> +   <string>ProtoRT Editor</string>
`Терминал Alpha.ProtoRt`.

2016-11-15 05:47 UTC, dstftw commented
Вообще, что тут делают коммиты 20 дневной давности уже давно слитые в мастер?

2016-11-15 09:22 UTC, vvkostenko requested changes

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/configdialog.cpp
> +    cd(new Ui::ConfigDialog)
Утечка памяти. `cd` не освобождается.

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/configdialog.cpp
> +void ConfigDialog::loadDeploy(QString &c_deploy)
`const`.

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/document.cpp
> +        return 0;
Во-первых, почему `0/1`, а не `false/true`?
Во-вторых, здесь, в случае усшешного сохранения вернется `0`, то есть `false`,  а не `true`, что выглядит нелогично. Метод `save` ддолжен возвращать `true` в случае успеха.

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/mainwindow.cpp
> +        textEdit->save();
Дублирование кода (59-75).

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/mainwindow.cpp
> +    textEdit->save();
Дублирование кода (32-48).

2016-11-15 09:22 UTC, vvkostenko commented on terminal/src/mainwindow.cpp
> +    for (int i = ui->tabWidget->count(); i >= 0; --i)
Опять невалидный индекс.

2016-11-15 10:35 UTC, dstftw requested changes

2016-11-15 10:35 UTC, dstftw commented on terminal/src/document.cpp
> +        return true;
Если файл открыть не удалось то вернется `true`, что не соответствует действительности.

2016-11-15 10:35 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +        }
Дублирование кода никуда не делось. Тот же самый код в методе `on_save_all_triggered`.

2016-11-15 10:35 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +            if(nfname != fname)
Почему имя файла до сохранения сравнивается с именем файла после сохранения, в чем смысл? Проверять нужно при успешном сохранении и сравнивать с названием таба.

2016-11-15 10:35 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +    doc->Document::setFileName(fileName);
`Document::` зачем?

2016-11-15 11:58 UTC, dstftw requested changes

2016-11-15 11:58 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +                setTabName(index, nfname);
Как было так и осталось (37-43, 57-63).

2016-11-15 11:58 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +        }
Как было так и осталось (37-44, 57-64).

2016-11-15 15:31 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +void MainWindow::setTabName(int index, QString name)
Опять ненужное копирование строки.

2016-11-16 09:57 UTC, dstftw requested changes

2016-11-16 09:57 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +    saving(textEdit);
```cpp
on_save_file_triggered()
{
	save(ui->tabWidget->currentIndex());
}


on_save_all_triggered()
{
	for (int i = 0; i < ui->tabWidget->count(); ++i)
		save(i);
}


save(int index)
{
	if (index == -1)
		return;

	auto doc = dynamic_cast<QTextEdit*> (ui->tabWidget->widget(index));
	if (!doc)
		return;
	
	if (!doc->save())
		return;
	
	QString nfname = textEdit->fileName();
	if(nfname != ui->tabWidget->tabText(index))
		setTabName(index, nfname);
}
```

2016-11-16 10:50 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +void MainWindow::saveDocument()
Не используется.

2016-11-16 10:50 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +void MainWindow::setTabName(int index, QString& name)
`const`.

2016-11-16 10:50 UTC, dstftw commented on terminal/src/mainwindow.cpp
> +    ui->tabWidget->currentWidget()->deleteLater();
`widget(index)->deleteLater()`.

2016-11-16 10:50 UTC, dstftw commented on terminal/src/mainwindow.h
> +    void saving(int index);
`saving` -> `saveDocument`.

2016-11-16 10:50 UTC, dstftw commented on terminal/src/mainwindow.h
> +    Document* currentDocument() const;
To remove.

2016-11-16 11:12 UTC, merged