Deploy communication protocol
Automiq/alpha.protort pull request #87
Opened 2016-11-14 12:57 UTC by dwlttpr

Наполнение для StatusResponse

2016-11-14 13:47 UTC, dstftw requested changes

2016-11-14 13:47 UTC, dstftw commented on node/tests/auto/tests_node.cpp
> +
^

2016-11-14 13:47 UTC, dstftw commented on node/tests/auto/tests_node.cpp
> +
^

2016-11-14 13:47 UTC, dstftw commented on protocol/src/src.pro
> +
^

2016-11-14 13:47 UTC, dstftw commented on protocol/src/protobuf/deploy.proto
> +    uint32 counter_out_bytes = 5;
Префикс `counter_` зачем?

2016-11-15 04:45 UTC, dwlttpr commented on node/tests/auto/tests_node.cpp
> +
Qtcreator сам их добавляет в конец файла. Честно

2016-11-15 05:39 UTC, dstftw commented on node/tests/auto/tests_node.cpp
> +
И в начало?

2016-11-15 05:39 UTC, dstftw commented on protocol/src/src.pro
> +
И в середину?

2016-11-15 05:46 UTC, dstftw commented
Вообще, что тут делают коммиты 20 дневной давности уже давно слитые в мастер?

2016-11-15 07:32 UTC, merged